### PR TITLE
Update NullabilityInfoContext.cs.pp with bug fix from MS repo

### PR DESCRIPTION
**Pull request by Shane32**
See:
- https://github.com/dotnet/runtime/pull/63556

### CODE REVIEW

**Comment by Shane32** [comment]
@SimonCropp When using this source-only repo, does the code get injected for all frameworks, or only pre-.NET 6 frameworks?  If the latter, is there any way to make this work in a .NET 6 environment, so that the fixed code is used rather than the buggy .NET 6 code?

**Comment by SimonCropp** [comment]
thanks for this. i will deploy it now.

> When using this source-only repo, does the code get injected for all frameworks, or only pre-.NET 6 frameworks

only pre-.NET 6 frameworks

>  is there any way to make this work in a .NET 6 environment, so that the fixed code is used rather than the buggy .NET 6 code?

not currently. TBH it is no a scenario that i considered. although it is obviously valid. thoughts on how it could be achieved? perhaps via compilation constant?

**Comment by SimonCropp** [comment]
or i could deploy a new nuget that has all the types in a diff namespace

**Comment by Shane32** [comment]
Between me and another person, we have found a multitude of bugs with `NullabilityInfoContext`.  But to be honest, it's unlikely most people would run into issues for my specific use case within GraphQL.NET.

Just for reference:
- https://github.com/dotnet/runtime/pull/63556
- https://github.com/dotnet/runtime/issues/63853
- https://github.com/dotnet/runtime/issues/63849
- https://github.com/dotnet/runtime/issues/63848
- https://github.com/dotnet/runtime/issues/63847
- https://github.com/dotnet/runtime/issues/63846
- https://github.com/dotnet/runtime/issues/63660
- https://github.com/dotnet/runtime/issues/63555

Plus another bug when a generic type definition of a generic class has a class constraint - but I have not created an issue yet.

> or i could deploy a new nuget that has all the types in a diff namespace

I'll let you know if it would be beneficial.  Thanks!!!

**Comment by sungam3r** [comment]
😕 What happens with the MS code?

**Comment by Shane32** [comment]
It is slated for .NET 7

**Comment by SimonCropp** [comment]
it should have been a nuget that is shipped out of band

**Pull request merged**
